config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'products/index2' => 'products#index2', as: 'index2_product'
  get 'products/index3' => 'products#index3', as: 'index3_product'# 全アイテムのステイタス一覧
  get 'products/index4' => 'products#index4', as: 'index4_product'
  get 'products/index5' => 'products#index5', as: 'index5_product'
  get 'products/index_document' => 'products#index_document', as: 'index_document'
  get 'products/new_document' => 'products#new_document', as: 'new_document'

  get 'products/index6' => 'products#index6', as: 'index6_product'
  get 'products/index7' => 'products#index7', as: 'index7_product'
  get 'products/index8' => 'products#index8', as: 'index8_product' # 製品の達成度
  get 'products/index9' => 'products#index9', as: 'index9_product' # 全アイテムの日付一覧

  get 'products/download' => 'products#download', as: 'download_product'
  get 'products/doc_download' => 'products#doc_download', as: 'doc_download_product'

  get 'products/process_design_download' => 'products#process_design_download', as: 'process_design_download'

  root to: 'products#top'
  
  resources :products 
  
  



       
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :files

  #空欄を防ぐ機能は付けたいが、Documentにも適用されて、うまく回避できなかった
  #validates :partnumber, presence: true


  #validates :documentname, presence: true
  #validate :start_end_check
  #validates :goal_attainment_level, numericality: { less_than_or_equal_to: 100, greater_than_or_equal_to: 1 }
  validate :range

  #【rails, Validation】開始日と終了日の逆転防止
  # https://zenn.dev/aosan/scraps/b8e0d4ebcb4fce
  #def start_end_check
  #  errors.add(:end_at,"は開始日より前の日付は登録できません。") unless
  #  self.start_time < self.end_at 
  #  end
  
  
  #def start_end_check
  #  errors.add(:end_at,"は開始日より前の日付は登録できません。") unless
  #  self.start_time < self.end_at 
  #  end
  
  #def start_end_check
  #  errors.add(:end_at,"は完了予定日より前の日付は登録できません。") unless
  #  self.deadline_at < self.end_at 
  #  end
  
  def range
    errors.add(:goal_attainment_level, "の値が不正です") unless 
    self.goal_attainment_level>=1 && self.goal_attainment_level<=100
    end

  

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
 
  def index2
    @products = Product.where(partnumber:params[:partnumber])
  end

  def index3
   #こちらを選択していた@products=Product.select("DISTINCT ON (partnumber,food) *").page(params[:page]).per(4)
   @products=Product.select("DISTINCT ON (partnumber,food) *")
   
    @mark_complate="完"
    @mark_WIP="仕掛"

    @user = current_user
  end

  def index9
    @products=Product.select("DISTINCT ON (partnumber,food) *")
    
     @user = current_user
   end

  def index4
    
  end

  def index5
    #https://qiita.com/ozin/items/f4aea5b244a6aa03caee
    #@products=Product.all
    @products=Product.with_attached_files
  end

  def index6
    #https://qiita.com/ozin/items/f4aea5b244a6aa03caee
    #@products=Product.all
    @products=Product.with_attached_files
  end

  def index7
    #https://qiita.com/ozin/items/f4aea5b244a6aa03caee
    #@products=Product.all
    @products=Product.with_attached_files
  end

  def index8
    @products = Product.where(partnumber:params[:partnumber])
  end

  def top
    #@products=Product.all.page(params[:page]).per(10)
    #@products=Product.all
    @products=Product.with_attached_files
    @user = current_user    
  end

  
  def index_document
    #@products=Product.all.page(params[:page]).per(10)
    #@products=Product.all
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
    @user = current_user
   
  end

  

  def index
    #@products=Product.all.page(params[:page]).per(10)
    #@products=Product.all
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
    @user = current_user
    
    
  end


  

  def new_document
    @product = Product.new
  end

  

  def new
    @product = Product.new
    
  end

  def create
    @product = Product.new(product_params)
    #@product.files = params[:product][:files]

    if @product.save
      redirect_to @product
    else
      if @product.documenttype=="製品"
      render "new"
      else
      render "new_document"
      end
      #if @product.documenttype=="製品"
      #  flash[:alert] = @product.errors.full_messages
      #  redirect_to new_product_url 
      #else
      #  flash[:alert] = @product.errors.full_messages
      #  redirect_to new_document_url
      #end
      
       

    end
  end

  def show
    #@product = Product.find(params[:id])
    if @product.files.attached?
         @product.files.each do |image| 
           fullfilename = rails_blob_path(image)
           @ext = File.extname(fullfilename).downcase
           if @ext== ".jpg" ||  @ext== ".jpeg" ||  @ext== ".png" ||  @ext== ".gif" 
             @Attachment_file = true
           else
             @Attachment_file = false
           end
         end      
    end   
  end

  # GET /cats/1/edit
  def edit
    #@product = Product.find(params[:id])
    @title=Product.find(params[:id])

    if @product.files.attached?
         @product.files.each do |image| 
           fullfilename = rails_blob_path(image)
           @ext = File.extname(fullfilename).downcase
           if @ext== ".jpg" ||  @ext== ".jpeg" ||  @ext== ".png" ||  @ext== ".gif" 
             @Attachment_file = true
           else
             @Attachment_file = false
           end
         end  
    end   
  end

  

  # PATCH/PUT /cats/1 or /cats/1.json
  def update
   #@product = Product.find(params[:id])
   product = Product.find(params[:id])
   #if params[:product][:detouch]=='1'
   if params[:product][:detouch]
       params[:product][:detouch].each do |image_id|
        #image = product.files.find(image_id)
        image = @product.files.find(image_id)
        image.purge
       end
   end

   #if product.update_attributes(product_params)
   #update_attributes は、
   #Rails 6.0 → 非推奨
   #Rails 6.1 → 廃止
   #https://qiita.com/kaito_suzuki/items/016f6d76a152f659064c
   
   if product.update(product_params)
    flash[:success] = "編集しました"
    redirect_to @product
   else
    render :edit
   end

 
  end

  # DELETE /cats/1 or /cats/1.json
  def destroy
    #@product = Product.find(params[:id])
    @product.destroy
    respond_to do |format|
      if @product.documenttype=="製品"
        format.html { redirect_to products_url, notice: "データは正常に削除されました。" }
      else
        format.html { redirect_to index_document_url, notice: "データは正常に削除されました。" }
      end
      
      format.json { head :no_content }
    end
  end

  def search
    @qd = Product.ransack(params[:qd])
    #@products = @qd.result
    @products = @qd.result(distinct: true)
    @user = current_user
    binding.pry
  end

  def download
    response.headers["Content-Type"] = "application/excel"
    response.headers["Content-Disposition"] = "attachment; filename=\"製品データ.xls\""
      #@date_from = Date.new(2014,3,1)
      #@date_to = Date.new(2014,3,31)
    #@product = Product.find(params[:id])
    #https://qiita.com/ozin/items/f4aea5b244a6aa03caee
    #@products=Product.all
    @products=Product.with_attached_files
    


      #@stocks = ProductStock
      #  .where(product_id: @product.id)
      #  .where(date: @date_from..@date_to)
      #  .order(:date)
    render 'data_download.xls.erb'
    
    
  end

  def doc_download
    response.headers["Content-Type"] = "application/excel"
    response.headers["Content-Disposition"] = "attachment; filename=\"文書データ.xls\""
      #@date_from = Date.new(2014,3,1)
      #@date_to = Date.new(2014,3,31)
    #@product = Product.find(params[:id])
    #@products=Product.all
    @products=Product.with_attached_files
      #@stocks = ProductStock
      #  .where(product_id: @product.id)
      #  .where(date: @date_from..@date_to)
      #  .order(:date)
    render 'data_doc_download.xls.erb'
    #render 'products/data_doc_download'
    
  end

  def process_design_download
    response.headers["Content-Type"] = "application/excel"
    response.headers["Content-Disposition"] = "attachment; filename=\"製造工程設計計画書／実績書.xls\""
    @products = Product.where(partnumber:params[:partnumber])
    render "process_design_download.xls.erb"
    #render 'products/process_design_download'
  end

  


  private

  def set_q
    @q = Product.ransack(params[:q])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:documentnumber,:documentcategory,:documenttype,:documentname,:documentrev,:start_time,:tasseido,:partnumber, :materialcode,:phase,:food,:goal_attainment_level,:deadline_at,:description,:end_at,:status,files:[])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container-fruid">
  <div class="table-responsive">
    <table class="table table-bordered">

  <thead>
    <tr>
     <table border="1"> 
     <th>項目</th>
      <th>ID</th>
    
      <th>図番</th>
      <th>材料コード</th>
      <th>フェーズ</th>
      <th>項目</th>
      <th>コメント</th>
      <th>登録日</th>
      <th>完了予定日</th>
      <th>完了日</th>
      <th>達成度(%)</th>
      <th>ステイタス</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% koumoku.each do |koumo| %>
    <% sonzai= false %>
      <tr>
        <td><%= koumo %></td>
      
        <% products.each do |pro| %>
     

          <% if pro.food==koumo %>
              <% if sonzai==true %>            
                <tr><td><%= koumo %></td>
              <% end %>
          <% sonzai=true %>

            <td><%= pro.id %></td>
            <td><%= pro.partnumber %></td>
            <td><%= pro.materialcode %></td>
            <td><%= pro.phase %></td>
            <td><%= pro.food %></td>
            <td><%= pro.description %></td>
            <td><%= l pro.start_time  %></td>
            <td><%= l pro.deadline_at  %></td>
            <% if pro.status=="完了" %>
              <td><%= l pro.end_at  %></td>
            <% else %>
              <td><%= "------"  %></td>
            <% end %>
            <td><%= pro.goal_attainment_level %></td>
            <td><%= pro.status %></td>
            <td><%= link_to '詳細', pro ,class:"btn btn-info"%></td>
            <td><%= link_to '編集', edit_product_path(pro) ,class:"btn btn-warning"%></td>
            <td><%= link_to '削除', pro, method: :delete, data: { confirm: '本当に削除しますか?' },class:"btn btn-danger" %></td>

            <%= render partial: "attached_file", locals: { pro: pro }  %>

          <% end %>
        <% end %>          
      </tr>
     <% end %>
    </tbody>
  </table>

  </div>
</div>

<br>
<%= link_to '戻る', products_path ,class:"btn btn-secondary"%>

app/views/products/_form3.html.erb
<table>
  <thead>

  <% jyunban=[] %>
  <% sta=[] %>
    <tr>
   
      <td><%="図番"%></td>
      <% koumoku.each do |koumo| %>
        <td><font size="3"><center><%= koumo %></center></font></td>
      <% end %>
    </tr>
  </thead>

  <tbody>
 
  <% partnumber=""%>
  <% products.each do |pro| %>
  <% input_aru=0 %>
    <% unless pro.partnumber==partnumber  %>
     
      <%  jyunban=jyunban.sort.reverse %>
      <% koumoku.each do |koumo| %>
      <% input_aru=0 %>
        <% catch(:out) do %>
          <% jyunban.zip(sta).each do |jyun,s| %>
            <% if jyun==koumo && s=="完了" %>
              <% input_ari=1 %>
              <td> <center><font size="4" color="blue"> <%=  @mark_complate  %> </font></center></td>
                   <% throw :out %>  
            <% end %>
            <% if jyun==koumo && s=="仕掛中" %>
              <% input_ari=1 %>
              <td> <center><font size="3" color="blue"> <%=  @mark_WIP  %> </font></center></td>
                   <% throw :out %>  
            <% end %>
          <% end %>
          <% if input_ari=0 && partnumber!="" %> 
             <td><center><font size="4" color="red"> <%= "-" %> </font></center></td>
          <% end %>
        <% end %>
      <% end %>
      <tr><td><%= "" %></td></tr>
      <td><%= pro.partnumber %></td> 
      <% jyunban=[] %>
      <% sta=[] %>
    <% end %>

  
  <% partnumber=pro.partnumber%>
    <% catch(:break_loop) do %>
      <% koumoku.each do |koumo| %> 
          <% if pro.food==koumo && pro.status=="完了"  %>
          <% input_ari=1 %>
          <% sta.push(pro.status) %>
          <% jyunban.push(koumo)%>          
          <% throw :break_loop %>             
          <% end %>
          <% if pro.food==koumo && pro.status=="仕掛中"  %>
          <% input_ari=1 %>
          <% sta.push(pro.status) %>
          <% jyunban.push(koumo)%>          
          <% throw :break_loop %>             
          <% end %>
      <% end %>
    <% end %>
  <% end %> 

  <%jyunban==jyunban.sort.reverse%>
  
  <% koumoku.each do |koumo| %>
        <% input_aru=0 %>
        <% catch(:out_break) do %>
              <% jyunban.zip(sta).each do |jyun,s| %>
                <% if jyun==koumo && s=="完了" %>
                  <% input_ari=1 %>
                  <td> <center><font size="4" color="blue"> <%=  @mark_complate  %> </font></center></td>
                       <% throw :out_break %>  
                <% end %>
                <% if jyun==koumo && s=="仕掛中" %>
                  <% input_ari=1 %>
                  <td> <center><font size="3" color="blue"> <%=  @mark_WIP  %> </font></center></td>
                       <% throw :out_break %>  
                <% end %>
              <% end %>
            
              <% if input_ari=0 %> 
                 <td><center><font size="4" color="red"> <%= "-" %> </font></center></td>
              <% end %>
        <% end %>
  <% end %>

  </tbody>
</table>
 
<br>
<%= link_to '戻る', products_path ,class:"btn btn-secondary"%>

app/views/products/_form9.html.erb
<table>
  <thead>

  <% jyunban=[] %>
  <% sta=[] %>
  <% deaddate=[] %>
  <% enddate=[] %>

    <tr>
   
      <td rowspan="2"><%="図番"%></td>
      <% koumoku.each do |koumo| %>
        <td colspan="2"><font size="3"><center><%= koumo %></center></font></td>  
        
      <% end %>
    </tr>
    <tr>
     
      <% koumoku.each do |koumo| %>
      <td><font size="3"><center>予定</center></font></td>
      <td><font size="3"><center>完了</center></font></td>
      <% end %>
    </tr>
  </thead>

  <tbody>
 
  <% partnumber=""%>
  <% products.each do |pro| %>
  <% input_aru=0 %>
    <% unless pro.partnumber==partnumber  %>

    <%  jyunban=jyunban.sort.reverse %>

     <!--
     <%= koumoku.sort.reverse %>
     新しくkoumokuを増やす場合は、index３の順番を、上記koumoku.sort.revrseと同じ順番になるように調整すること
      
      <%  jyunban=jyunban.zip(sta,deaddate,enddate).sort! %>
       sortの後に!をつけると、配列自体が変更される
       jyunbanは、2次元配列に変換されている為、下でjyunとsで表現できる 
      -->
      <% koumoku.each do |koumo| %>
      <% input_aru=0 %>
        <% catch(:out) do %>
          <% jyunban.zip(sta).each do |jyun,s,d,e| %>
          
          
            <% if jyun==koumo && s=="完了" %>
              <% input_ari=1 %>
               <td> <center><font size="4" color="blue"> <%=  d.strftime('%y/%m/%d') %> </font></center></td>
               <td> <center><font size="4" color="blue"> <%=  e.strftime('%y/%m/%d')  %> </font></center></td>
                   <% throw :out %>  
            <% end %>
            <% if jyun==koumo && s=="仕掛中" %>
              <% input_ari=1 %>
              <td> <center><font size="3" color="magenta"> <%=  d.strftime('%y/%m/%d')  %> </font></center></td>
              <td><strong><center><font size="4" color="red"> <%= "　━　" %> </font></center></strong></td>
                   <% throw :out %>  
            <% end %>
          <% end %>
          <% if input_ari=0 && partnumber!="" %> 
             <td><strong><center><font size="4" color="red"> <%= "　━　" %> </font></center></strong></td>
             <td><strong><center><font size="4" color="red"> <%= "　━　" %> </font></center></strong></td>
          <% end %>
        <% end %>
      <% end %>
      <tr><td><%= "" %></td></tr>
      <td><%= pro.partnumber %></td> 
      <% jyunban=[] %>
      <% sta=[] %>
      <% deaddate=[] %>
      <% enddate=[] %>
    <% end %>

  <% partnumber=pro.partnumber%>
    <% catch(:break_loop) do %>
      <% koumoku.each do |koumo| %> 
          <% if pro.food==koumo && pro.status=="完了"  %>
            <% input_ari=1 %>
            <% sta.push(pro.status) %>
            <% jyunban.push(koumo)%>
            <% deaddate.push(pro.deadline_at)%>
            <% enddate.push(pro.end_at)%>
            <% throw :break_loop %>             
          <% end %>
          <% if pro.food==koumo && pro.status=="仕掛中"  %>
            <% input_ari=1 %>
            <% sta.push(pro.status) %>
            <% jyunban.push(koumo)%>
            <% deaddate.push(pro.deadline_at)%>
            <% enddate.push(pro.end_at)%>
            <% throw :break_loop %>             
          <% end %>
      <% end %>
    <% end %>
  <% end %> 

    <!--
  
  <%jyunban=jyunban.zip(sta).sort.reverse%>
  

  <%jyunban=jyunban.zip(sta).sort%>
  -->
 
  <%jyunban==jyunban.sort.reverse%>
  <% koumoku.each do |koumo| %>
        <% input_aru=0 %>
        <% catch(:out_break) do %>
        
              
              
               <% jyunban.zip(sta).each do |jyun,s,d,e| %>
              
                <% if jyun==koumo && s=="完了" %>
                  <% input_ari=1 %>
                  
                  <td> <center><font size="4" color="blue"> <%=  d.strftime('%y/%m/%d') %> </font></center></td>
                  <td> <center><font size="4" color="blue"> <%=  e.strftime('%y/%m/%d')  %> </font></center></td>
                  <% throw :out_break %>  
                <% end %>
                <% if jyun==koumo && s=="仕掛中" %>
                  <% input_ari=1 %>
                 <td> <center><font size="3" color="magenta"> <%=  d.strftime('%y/%m/%d')  %> </font></center></td>
                 <td><strong><center><font size="4" color="red"> <%= "　━　" %> </font></center></strong></td>
                  <% throw :out_break %>  
                <% end %>
              <% end %>
            
              
              <% if input_ari=0 %>
                  <td><strong><center><font size="4" color="red"> <%= "　━　" %> </font></center></strong></td>
                  <td><strong><center><font size="4" color="red"> <%= "　━　" %> </font></center></strong></td>
              <% end %>
        <% end %>
  <% end %>
  
  

  </tbody>
</table>
 
<br>
<%= link_to '戻る', products_path ,class:"btn btn-secondary"%>

app/views/products/_form_attainment.html.erb
<head>
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
</head>


       <% timeline1=[] %>
       <% timeline2=[] %>

       <% koumoku.each do |koumo| %>
        <% ti=0 %>
          <% products.each do |pro| %>
             <% if pro.documentname==koumo %>
               <% timeline1=[pro.documentname,pro.goal_attainment_level]%>
               <% ti=1 %>
             <% end %>
          <% end %>
          <% if ti==0 %>
            <% timeline1=[koumo,0]%>
          <% end %>
          <% timeline2.push(timeline1) %>
        
        <% end %>
       
      

  
   <%= bar_chart timeline2,max:"100" ,width: "1200px", height: "500px",xtitle: "達成度(%)", ytitle: "項目",suffix: "%" %>
   
  


<br>
<%= link_to '戻る', index_document_path ,class:"btn btn-secondary"%>

app/views/products/edit.html.erb
<h1>編集</h1>
<% if @product.documenttype=="製品"%>
<%= render partial: "input", locals: { product: @product ,ext: @ext } %>
<% else %>
<%= render partial: "input_document", locals: { product: @product ,ext: @ext } %>
<% end %>

app/views/products/edit_document.html.erb
<h1>編集</h1>
<%= render partial: "input_document", locals: { product: @product ,ext: @ext } %>

app/views/products/list.html.erb
<h1>IATF APQP List</h1>

app/views/products/show.html.erb
<h1>詳細</h1>

<% if @product.documenttype=="製品"%>
  <table>
    <thead>
      <tr>
      <table border="1">
        <th>ID</th>
        <th>Doc.Type</th>
        <th>図番</th>
        <th>材料コード</th>
        <th>フェーズ</th>
        <th>項目</th>
        <th>コメント</th>
        <th>登録日</th>
        <th>完了予定日</th>
        <th>完了日</th>
        <th>達成度(%)</th>
        <th>ステイタス</th>   
      </tr>
    </thead>

    <tbody>
        <% if @product.status=="完了" %>
          <% @product.goal_attainment_level=100 %>
        <% end %>
    
        <tr>
          <td><%= @product.id %></td>
          <td><%= @product.documenttype %></td>
          <td><%= @product.partnumber %></td>
          <td><%= @product.materialcode %></td>
          <td><%= @product.phase %></td>
          <td><%= @product.food %></td>
          <td><%= @product.description %></td>
          <td><%= l @product.start_time  %></td>
          <td><%= l @product.deadline_at  %></td>
          <% if @product.status=="完了" %>
                <td><%= l @product.end_at  %></td>
              <% else %>
                <td><%= "------"  %></td>
              <% end %>
          <td><%= @product.goal_attainment_level %></td>
          <td><%= @product.status %></td>
          <%= render partial: "attached_file", locals: { pro: @product }  %>      
        </tr> 
    </tbody>
  </table>

  <br>  
  <br>

    <p>
    <strong>画像:</strong>
    <% if @product.files.attached? && @Attachment_file %>
         <% @product.files.each do |image| %>
           <% fullfilename = rails_blob_path(image) %>
           <% @ext = File.extname(fullfilename).downcase %>
           <% if @ext== ".jpg" ||  @ext== ".jpeg" ||  @ext== ".png" ||  @ext== ".gif" %> 
                 <br>
                 <%= image.blob.filename %> <br>
                 <%= image_tag image.variant(resize: "200x200") %>
           <% end %>
         <% end %>
    <%else%>
      <strong>無し </strong> <br>
    <% end %>

    <br><br>
    <% if @product.files.attached? %>
         <% @product.files.each do |image| %> 
           <% fullfilename = rails_blob_path(image) %>
           <% ext= File.extname(fullfilename).downcase %>
         <% end %>
    <% end %>
      <strong>ダウンロード:</strong>
      <br>

    <% if @product.files.attached? %>
         <% @product.files.each do |image| %> 
           <%= link_to image.blob.filename  ,rails_blob_path(image)%> <br>
         <% end %>

    <% end %>
    </p>

  <%= link_to '戻る', products_path ,class:"btn btn-secondary"%>

<% else %>

<table>
  <thead>
  
    <tr>
    <table border="1">
      <th>ID</th>
      <th>Doc.Type</th>
      <th>文書名</th>
      <th>文書番号</th>
      <th>文書カテゴリー</th>
      <th>コメント</th>
      <th>登録日</th>
      <th>完了予定日</th>
      <th>完了日</th>
      <th>達成度(%)</th>
      <th>ステイタス</th>  
      
    </tr>
  </thead>

  <tbody>
      <% if @product.status=="完了" %>
        <% @product.goal_attainment_level=100 %>
      <% end %>
    
      <tr>
        <td><%= @product.id %></td>
        <td><%= @product.documenttype %></td>
        <td><%= @product.documentname %></td>    
        <td><%= @product.documentnumber %></td>
        <td><%= @product.documentcategory %></td>
        <td><%= @product.description %></td>
        <td><%= l @product.start_time  %></td>
        <td><%= l @product.deadline_at  %></td>
        <% if @product.status=="完了" %>
              <td><%= l @product.end_at  %></td>
            <% else %>
              <td><%= "------"  %></td>
            <% end %>
        <td><%= @product.goal_attainment_level %></td>
        <td><%= @product.status %></td>
       <%= render partial: "attached_file", locals: { pro: @product }  %>
      </tr> 
  </tbody>
</table>

<br>
  
  <p>
  <strong>画像:</strong>
  <% if @product.files.attached? && @Attachment_file %>
       <% @product.files.each do |image| %>
         <% fullfilename = rails_blob_path(image) %>
         <% @ext = File.extname(fullfilename).downcase %>
           <% if @ext== ".jpg" ||  @ext== ".jpeg" ||  @ext== ".png" ||  @ext== ".gif" %> 
               <br>
               <%= image.blob.filename %> <br>
               <%= image_tag image.variant(resize: "200x200") %>
           <% end %>
       <% end %>
  <%else%>
    <strong>無し </strong> <br>
  <% end %>
  <br><br>
  
  </p>
  <p>
  <% if @product.files.attached? %>
       <% @product.files.each do |image| %> 
         <% fullfilename = rails_blob_path(image) %>
         <% ext= File.extname(fullfilename).downcase %>
       <% end %>
  <% end %>
    <strong>ダウンロード:</strong>
    <br>

  <% if @product.files.attached? %>
       <% @product.files.each do |image| %> 
         <%= link_to image.blob.filename  ,rails_blob_path(image)%> <br>
       <% end %>

  <% end %>
  </p>

<%= link_to '戻る', index_document_path ,class:"btn btn-secondary"%>

<% end %>